language: csharp
solution: WebpageScreensaver.sln
before_build:
  - nuget restore WebpageScreensaver.sln
script:
  - msbuild /p:Configuration=Release WebpageScreensaver.sln
#  - mono OpenCover.Console.exe -register:user -target:"./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe" -targetargs:"./MyProject.Tests/bin/Release/MyProject.Tests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:".\MyProject_coverage.xml"
#  - codecov -f "MyProject_coverage.xml" "93a81734-84ae-4432-9a05-8c523c674228"
