language: csharp
solution: Web-Page-Screensaver.sln
before_build:
  - nuget restore Web-Page-Screensaver.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Web-Page-Screensaver.sln
  - pwd
  - ls ./
  - ls ./testrunner/
  - ls ./testrunner/NUnit.ConsoleRunner.3.9.0/
  - ls ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/
  - ls ./MyProject.Tests
  - ls ./MyProject.Tests/bin
  - ls ./MyProject.Tests/bin/Release
  - mono OpenCover.Console.exe -register:user -target:"./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe" -targetargs:"./MyProject.Tests/bin/Release/MyProject.Tests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:".\MyProject_coverage.xml"
  - codecov -f "MyProject_coverage.xml" "93a81734-84ae-4432-9a05-8c523c674228"
